#!/usr/bin/env python3
"""
Minimal SSOT maintenance helper for MaraudersMapMD skill repository.

Source of truth:
- SKILL.md

Repository policy:
- Do NOT commit generated MaraudersMap artifacts (docs/MaraudersMap/**).
- External users install SKILL.md directly.

This script no longer generates section/index/shards artifacts by default.
Use it to check or clean generated byproducts.
"""

from __future__ import annotations

import argparse
import shutil
from dataclasses import dataclass
from pathlib import Path


GENERATED_ROOT = Path("docs") / "MaraudersMap"


@dataclass(frozen=True)
class Args:
    source: str
    check: bool
    clean: bool


def _list_generated_paths(repo_root: Path) -> list[Path]:
    root = repo_root / GENERATED_ROOT
    if not root.exists():
        return []
    return [path for path in sorted(root.rglob("*")) if path.is_file()]


def main() -> int:
    parser = argparse.ArgumentParser(
        description="Check/clean generated MaraudersMap artifacts for minimal SSOT repo policy."
    )
    _ = parser.add_argument(
        "--source",
        default="SKILL.md",
        help="Path to source SKILL.md (single source of truth).",
    )
    _ = parser.add_argument(
        "--check",
        action="store_true",
        help="Exit non-zero if generated MaraudersMap artifacts exist.",
    )
    _ = parser.add_argument(
        "--clean",
        action="store_true",
        help="Delete generated MaraudersMap artifacts under docs/MaraudersMap.",
    )
    raw: dict[str, object] = vars(parser.parse_args())
    args = Args(
        source=str(raw.get("source", "SKILL.md")),
        check=bool(raw.get("check", False)),
        clean=bool(raw.get("clean", False)),
    )

    repo_root = Path.cwd().resolve()
    source_path = (repo_root / args.source).resolve()
    if not source_path.exists():
        raise FileNotFoundError(f"Source not found: {source_path}")

    generated_files = _list_generated_paths(repo_root)

    if args.check:
        if generated_files:
            print(
                "Generated MaraudersMap artifacts detected (should not be committed):"
            )
            for path in generated_files:
                print(f"- {path.relative_to(repo_root)}")
            return 1
        print("OK: no generated MaraudersMap artifacts found.")
        return 0

    if args.clean:
        generated_root = repo_root / GENERATED_ROOT
        if generated_root.exists():
            shutil.rmtree(generated_root)
            print(f"Removed generated artifacts: {GENERATED_ROOT}")
        else:
            print("No generated artifacts to clean.")
        return 0

    print("Minimal mode: no artifact generation performed.")
    if generated_files:
        print("Generated artifacts currently exist. Run with --clean to remove them.")
    else:
        print("No generated artifacts detected.")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
